apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: emr-demo
spec:
  replicas: 5
  revisionHistoryLimit: 3
  selector:
    matchLabels: { app: emr-demo }
  template:
    metadata:
      labels: { app: emr-demo }
    spec:
      containers:
        - name: emr-demo
          image: argoproj/rollouts-demo:yellow    # <-- the one line you change per release
          ports: [{ containerPort: 8080 }]
          resources:
            requests: { cpu: 5m, memory: 32Mi }
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { }
        - setWeight: 60
        - pause: { duration: 30 }
